### ISSUE TITLE
Support secondary stack for returning dynamically sized objects

### ISSUE THREAD

**Issue by jklmnn** [Componolit/componolit#109]

**Comment by jklmnn** [comment]
I added a simple test that forces the compiler into using the secondary stack (https://github.com/jklmnn/genode/commit/0b6af25fedb77c918874e42498cd18dbf63e4957). The compilation marks the following symbols as missing:
 - `ada__exceptions__reraise_occurrence_no_defer`
 - `ada__exceptions__save_occurrence`
 - `system__secondary_stack__ss_allocate`
 - `system__secondary_stack__ss_mark`
 - `system__secondary_stack__ss_release`
 - `system__soft_links__get_current_excep`
 - `system__soft_links__get_gnat_exception`
 - `system__soft_links__get_jmpbuf_address_soft`
 - `system__soft_links__set_jmpbuf_address_soft`

**Comment by senier** [comment]
I guess we need to find out our selves. The following [FAQ answer](https://www.mapusoft.com/frequently-asked-questions-about-ada-cc-changer/) of an Ada-to-C translator was revealing:

> Q: What is “rts_ss_mark” and “rts_ss_release” functions appearing in my converted code?  I’m not sure I’m following what’s going on there…

> Ada uses a “secondary stack” to hold locally declared objects and temporaries whose size is not known at compile time.  This secondary stack is managed using a “mark/release” discipline (for background, see “mark-and-release” in http://www.flounder.com/memory_allocation.htm).  “rts_ss_mark” does a “mark” on the secondary stack, “rts_ss_release” releases everything on the secondary stack back to the specified mark.  In the above example, a “mark” is saved into pointer_1 at the beginning of a series of operations, and then a “release” is performed at appropriate points to recover the storage that had been allocated on the secondary stack, by operations such as “rts_ss_char_concat” which concatenates two strings into a temporary result on the secondary stack.

The referenced section says:

> Mark-and-Release

> For some algorithms, the best allocator is the one from Pascal 1.0: Mark-and-release. In this algorithm, you issue a "mark" request which marks the current heap.  Then you allocate trivially by simply incrementing a pointer into the free space.  When you are done, you issue a "release" which resets the free storage pointer to the "mark", thus freeing up everything that was allocated after the "mark".

> This is a pretty severe restriction on allocation.  Everything allocated after the "mark" operation is implicitly freed.  All of it.  Not one object can live beyond the "release" operation if it was allocated after the "mark".

**Comment by jklmnn** [comment]
Current design idea:

 - meta data registry that maps threads to meta data
 - `SS_Mark`: Check if thread is in registry, if not allocate Genode secondary stack and add mark to meta data, if yesonly return mark
 - `SS_Release`: go back to mark given in release, calculate stack pointer
 - `SS_Allocate`: calculate new stack pointer
 - `SS_Free`: throw everythign away

The mark is a meta data object that is prependet to each allocated part of the stack. The last mark is saved in the registry. If release is called the mark from the registry is taken and the stack is unwinded until the mark given is discovered. To discover the last mark we need to know how much stack is used after it. This information needs to be updated on each call of `SS_Allocate`.

Each Mark has two fields:
 - ID: 32 bit, if zero this field is not used (for registry)
 - Size: 32 bit, bytes to the next mark

**Comment by jklmnn** [comment]
The size of the stack must be something below 1M. When choosing exactly 1M I get a Stack_too_large exception. I assume this happens because the Stack size is 1M but some part of the Stack is needed for meta data.
I have chosen 768k now.

**Comment by jklmnn** [comment]
WIth https://github.com/jklmnn/genode/commit/45185fa4bfe48fdd6783f78d6bca38fbfd6a0ae7 I have moved the implementation of the stack logic into a separate package that can be built with the default runtime in GPS. This enables the usage of GPS for proof and testing.

I also think about refactoring the structure of the rts dir. Currently only the packages that shall be tested are in the separate `libsrc` directory. I think we should split the directory into ada and c++ and the ada files into those that provide the actual rts bindings and those that implement the rts logic in separate packages.

**Comment by jklmnn** [comment]
It seems that on x86_32 `SS_Release` is always called with `Mark_Id = 0` which causes it to fail. I added an edge case that the mark is set to the base if it is zero and this seems to work for the Test on Genode. But it still seems a bit fishy to me.
My first assumption was that I chose the wrong integer types between C and Ada causing the value to be in the wrong 32bit but this is a compiler interface which only uses Ada types (which should stay consistent).
Another possibility could be that at build time the wrong memory size is chosen. The Runtime provides different `system-<arch>.ads` files that define `Memory_Size` which itself is used to define the `Address` type. In the generic `system.ads` `Memory_Size` is defined as `Memory_Size  : constant := 2 ** Standard'Address_Size;`. I could not find any definition for it but only

> Standard'Address_Size (Standard is the only allowed prefix) is a static constant giving the number of bits in an Address. It is the same value as System.Address'Size, but has the advantage of being static, while a direct reference to System.Address'Size is nonstatic because Address is a private type.

I logged the size of `System.Address` and it is 32 on x86_32 and 64 on x86_64 which is what I expected. This doesn't explain why SS_Release gets null pointer as mark.

**Comment by senier** [comment]
My suspicion is that the mark is actually meant to be an offset into the secondary stack (and the ia32 implementation just requests to reset the stack completely). If we implemented it as such, wouldn't that remove the special case?

**Comment by jklmnn** [comment]
The fact alone that `SS_Release` gets something else than we have returned from `SS_Mark` means that either something is broken or the compiler makes assumptions we currently don't know.
The returned zero could beside being an offset also just a tag for the Mark (in which case we would have to store meta data again).
In any case our current test only creates scenarios that lets the compiler release the stack completely. Before changing or fixing our implementation I will create a test that forces the compiler to release the stack somewhere in the middle and analyze the behaviour.

**Comment by jklmnn** [comment]
I have implemented this test in https://github.com/jklmnn/genode/commit/3041bcc583404b257e8fce95cc8cc81b7364fd75. On x86_64 these releases are called with the addresses set at the previous calls to mark. But on x86_32 they are always called with 0. I doubt that this is the intended behaviour as it would corrupt the stack.

Nevertheless using only the offset instead of the full address would have two advantages:
 - The address calculation in `SS_Release` could be simplified or even removed without affecting the other functions.
 - We could fall back to using 32 bit values (which could solve the issue) what would be sufficient to map all offsets.

**Comment by jklmnn** [comment]
I have issued https://github.com/genodelabs/genode/pull/2810 and will close this once the PR is merged.

**Comment by senier** [comment]
Did you solve the x86_32 issue?

**Comment by jklmnn** [comment]
Yes I have implemented the `Mark_Id` as a record in https://github.com/jklmnn/genode/commit/0029eecb5912fea2f99d0b3266882f182cf5298f which solved the issue.

**Comment by senier** [comment]
I see. Well done!

**Comment by jklmnn** [comment]
In the system.ads provided by the gcc port the following line exists:
`pragma Restrictions (No_Implicit_Dynamic_Code);`
with the following description:

> We want to avoid trampolines in the compiler, so it can be used in systems which prevent execution of code on the stack, e.g. in windows environments with DEP (Data Execution Protection) enabled.

In Ada some instantiations of generic packages either on subprogram or library level (I tried to use amatrix with jwx on Genode) seem to generate code on the stack that gets executed. If this is the case the build fails with `violation of restriction "NO_IMPLICIT_DYNAMIC_CODE"`.

The easy fix would be to remove this line but I'm not 100% sure about the implications on Genode. Maybe @nfeske can say something about this?

Generally there are only two options:
 - removing this pragma and live with code on the stack
 - keeping it and working around it

The second option should only be chosen if anything else fails since it seems to limit the use of generics considerably.
The first option could be implemented by either patching it out of the generic system.ads (which could fail of the port is updated but that shouldn't happen that often) or by using a system specific system.ads that does not have this line (e.g. system-linux-x86_64.ads; that would require to choose the correct file at compilation time, also it could still require changes due to Linux specific properties).
A third option could be to supply a custom Genode specific system.ads in the Genode repository.

**Comment by jklmnn** [comment]
Fixed by https://github.com/genodelabs/genode/pull/2810.
