### ISSUE TITLE
Investigate microcode update options for Genode

### ISSUE THREAD

**Issue by senier** [Componolit/componolit#114]
Microcode updates can be essential for stability and security of a system as demonstrated by the mitigations rolled out to counter the recent Meltdown and Spectre vulnerabilities. While microcode updates should be done in the BIOS, we do not want rely on BIOS vendors who may not provide timely updates or no updates at all. Hence, microcode must be updated by the OS.

There are a number of restrictions when to apply microcode updates. Generally, this should be done [as early as possible](https://gitlab.com/iucode-tool/iucode-tool/blob/master/README). The goal of this issue is to investigate what is required to update microcode from withing Genode and what mechanisms are required.

**Comment by nfeske** [comment]
That's an important issue. Since it refers to the foundational part of Genode, would you mind moving the discussion over to Genode's issue tracker? This way, it will get the attention of all regular Genode contributors.

**Comment by senier** [comment]
Good idea. Closing this issue in favor of genodelabs/genode#2762.
