### ISSUE TITLE
Ada exception handling

### ISSUE THREAD

**Issue by jklmnn** [Componolit/componolit#129]
While building Acats I noticed that gnat seems to generate specific function calls for the raise of each exception. In the case of Acats these are
```
acats.lib.so: undefined reference to `__gnat_rcheck_CE_Length_Check'
acats.lib.so: undefined reference to `__gnat_rcheck_CE_Overflow_Check'
acats.lib.so: undefined reference to `__gnat_rcheck_CE_Invalid_Data'
acats.lib.so: undefined reference to `system__arith_64__add_with_ovflo_check'
acats.lib.so: undefined reference to `__gnat_rcheck_CE_Range_Check'
```

It probably would make sense to provide these symbols with the runtime (which we need anyway) and create a useful handling for them (e.g. throwing a specific C++ exception that could be used by surrounding C++ code.
Also it might make sense to examine the expected arguments in this case to extract the excption message (if this is possible) and propagate it to C++ (or at least print it in a warning/error).

**Comment by senier** [comment]
Very good point - I fully agree. Passing on messages would be gorgeous!

**Comment by senier** [comment]
The other direction is also very interesting, but we should open a new issue. What you mention aligns with what @nfeske mentioned recently - calling a proven XML parser from C++ and then relying on the correctness of the XML data structure without any further checks.

**Comment by jklmnn** [comment]
The exception functions are defined in a-except.ads so it would make sense to create our own implementation of this package.
They are declared as follows:
```
procedure Rcheck_CE_Explicit_Raise (File : System.Address; Line : Integer);
```
and then exported.

File is a C string that contains the file name in which the exception occured and Line is the corresponding line number.

https://github.com/jklmnn/genode/commit/ca9c210c61101034de6043bf9ac536d835676f53 contains a prototype implementation. It gets called when the `Program_Error` is raised and throws a generic `Genode::Exception`. Currently the error message would be printed even if the C++ exception is catched. But there should be a way to add the file and line number to the C++ exception. Also I currently haven't found a way to get exception messages from Ada. For the predefined exceptions there are reason string in a-except.ads.

**Comment by jklmnn** [comment]
When creating a custom exception, the following symbols are required:
```
__gnat_raise_exception
system__exception_table__register_exception
```

**Comment by jklmnn** [comment]
The missing symbols have been fixed in the course of the implementation of https://github.com/jklmnn/genode/commit/a19713aa1a43bbced2829cdb2ae1a387b7d2bd98.

**Comment by jklmnn** [comment]
This is fixed by https://github.com/genodelabs/genode/pull/2882.
