### ISSUE TITLE
Autogenerated Genode Interface

### ISSUE THREAD

**Issue by jklmnn** [Componolit/componolit#132]
With `g++ -c –fdump-ada-spec cpplib.cpp` CPP code can be used to autogenerate Ada specification files. This could be used to provide specs for the Genode API.

@senier: this could replace #127 since we won't need a manually built Genode interface.

**Comment by senier** [comment]
Indeed, but first let's see how viable this approach is ;-)

**Comment by jklmnn** [comment]
There are currently three major problems:
 - [ ] The autogenerated code contains contructs like `type util_meta_h.Empty is record` that are not allowed in Ada (note the `.` in the record name).
 - [ ] C++ functions starting with an underscore are ignored and ommitted with a comment `--  skipped func _underscore`.
 - [ ] The generated spec does not reflect Genodes namespace hierarchy and creates package names from file paths, namespaces and class names with underscores which is a rather ugly interface.

**Comment by jklmnn** [comment]
Duplicate of #127.
