### ISSUE TITLE
Evaluate clang to parse Genode headers

### ISSUE THREAD

**Issue by jklmnn** [Componolit/componolit#141]
To see if creating a tool based on clang is feasible an evaluation is required if clang can parse Genodes headers (or if not how much effort is needed to fix this). Note that this does not include compilation of any sources but only parsing the headers to get size and name of classes and datatypes and names of their functions.

**Comment by senier** [comment]
That raises another question: Can we draw the class sizes for gcc/gnat from an analysis done using clang? In other words, is that compatible? Opinions, @treiher?

**Comment by treiher** [comment]
I guess the [class sizes depend on the ABI](https://stackoverflow.com/a/14511054). As both implement the [Itanium C++ ABI](https://itanium-cxx-abi.github.io/cxx-abi/), GCC and Clang should be compatible in this matter.

**Comment by jklmnn** [comment]
@senier the stackoverflow link also explains the behaviour we saw when we tried to build our own class in Ada and got an error about an element not being aligned at 64 bits.

**Comment by jklmnn** [comment]
The generator should generate Ada packages from C++ classes and Namespaces. It should do a lexical mapping, e.g. `Namespace1::Namespace2::Class` should become `Namespace1.Namespace2.Class`.
The first tests should consist of source C++ headers/source files and the target Ada specs. The test cases should include (non-exhaustive list):
 - simple class
 - inheritance
 - namespaces
 - classes as member

Furthermore the test fixtures themselves need to be tested for correctnes by compiling the Ada/C++ sources and running their binaries.

The development will take place in https://github.com/Componolit/capdpa.

**Comment by senier** [comment]
Closing this issue, as we handle binding generation in  https://github.com/Componolit/capdpa now.
